export const USER_INFO = "USER_INFO";
export const ON_POST_PUBLISH = "ON_POST_PUBLISH";
export const ON_CONNECTIONS_UPDATE = "ON_CONNECTIONS_UPDATE";
export const ON_CHAT_MESSAGE = "ON_CHAT_MESSAGE";
export const SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE";

export default {
  USER_INFO,
  ON_POST_PUBLISH,
  ON_CONNECTIONS_UPDATE,
  SEND_CHAT_MESSAGE,
  ON_CHAT_MESSAGE
};
