export const USER_INFO = "USER_INFO";
export const ON_MESSAGE_PUBLISH = "ON_MESSAGE_PUBLISH";
export const ON_CONNECTIONS_UPDATE = "ON_CONNECTIONS_UPDATE";

export default {
  USER_INFO,
  ON_MESSAGE_PUBLISH,
  ON_CONNECTIONS_UPDATE
};
